[package]
name = "advoc25"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
multisets = "0.0.0"
nalgebra = "0.33.2"
num = "0.4.3"
num-rational = "0.4.2"
regex = "1.11.1"
unordered-pair = "0.2.5"
const_format = "0.2.35"
